### ISSUE TITLE
wrong Nullable

### ISSUE THREAD

**Issue by rodislav** [Meiendorf/becoming_0#4]
Hello, please use other Nullable or create your own, the one you used is from deprectaed package. everything that contains **sun** should be ignored.

--> https://github.com/Meiendorf/becoming_0/blob/master/src/contactList/repository/InMemoryRepo.java#L3

**Comment by Meiendorf** [comment]
The you need to fix it too in your implementation of contact list! :)
https://github.com/becoming/0-java-fundamentals/blob/026557f2b55e53820eae97ff29f2d4f99abbcbff/src/junior/contactlist/repository/InMemoryContactsRepo.java#L3

**Comment by rodislav** [comment]
indeed, please open an issue.
